version: '3.7'

services:

  node:
    container_name: nodeapp
    image: nodeapp
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PACKAGES: "vim wget curl"
    ports:
      - "3000:3000"
    networks:
      - nodeapp-network
    volumes:
      - ./logs:/var/www/logs
    environment:
      - NODE_ENV=production
      - APP_VERSION=1.0
    depends_on: 
      - mongodb
      
  mongodb:
    container_name: mongodb
    image: mongo
    volumes:
    - mongodb:/data/db
    networks:
      - nodeapp-network
volumes:
  mongodb: {}

networks:
  nodeapp-network:
    driver: bridge
